import { Session } from 'next-auth';
import { SessionProvider } from 'next-auth/react';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
    session,
}: {
    children: React.ReactNode;
    session: Session;
}) {
    return (
        <html lang="en">
            <SessionProvider session={session}>
                <body>{children}</body>
            </SessionProvider>
        </html>
    );
}
